per_page: 10
width_limit: 200
height_limit: 200
number_word: 20
limit_minutes: 20
size_word: "100x100"
fillter_words:
  - "learned"
  - "not_learn"
  - "all"
time_lesson: 1200
image_user: "90x90"
length_title: 23
activity:
  window: 2
